### ISSUE TITLE
Too lenghty naming

### ISSUE THREAD

**Issue by kootenpv** [dropbox/pb-jelly#124]
I have a proto file called `enums.proto`

Is there a way not to use it like:

    use proto_enums::proto_enums::Error;

but instead generate it with one of the following (or another suggestion)

    use proto::enums::Error;
    use proto_enums::enums::Error;

**Comment by nipunn1313** [comment]
Can you provide an example. All the examples in https://github.com/dropbox/pb-jelly/tree/main/examples don't seem to have the pattern you're describing.

For example:
https://github.com/dropbox/pb-jelly/blob/main/examples/src/basic/main.rs
