### ISSUE TITLE
Migrate codegen.py to Python3

### ISSUE THREAD

**Issue by ParkMyCar** [dropbox/pb-jelly#37]
Python2 is dead, long live python2!

`codegen.py` in the `pb-jelly-gen` crate is a `protoc` plugin that powers the Rust code generation. We should migrate this to python3

**Comment by mitsuhiko** [comment]
In which way does it not support Python 3?

**Comment by craftytrickster** [comment]
> 
> 
> In which way does it not support Python 3? Looks like it supports Python 3 just fine.

It says specifically in the README that it requires python 2. 

https://github.com/dropbox/pb-jelly/blob/master/README.md#generating-rust-code

If this is not the case, the README should be updated

**Comment by mitsuhiko** [comment]
Seems like an oversight. It appears to run on Python 3, it uses six internally and the main README calls out installing Python 3.

**Comment by nipunn1313** [comment]
Yeah - I believe the script is actually python2/python3 compatible
(internally at DBX - it's used in multiple environments, some of which are python3 and some of which are still python2)

**Comment by nipunn1313** [comment]
The type annotations are py2 compatible which may be the source of the confusion

**Comment by nipunn1313** [comment]
I updated the comment in README to correctly reference this and filed #40
