### ISSUE TITLE
Drop Python2 Compatibility

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/pb-jelly#40]
Inline the mypy annotations
Remove reference to six library

We should wait until python2 end-of-lifes before completing this task!

**Comment by joshuawarner32** [comment]
Isn't python2 already EOL'd? https://www.python.org/doc/sunset-python-2/

**Comment by nipunn1313** [comment]
ah whoops! I somehow (incorrectly) thought it EOL'd at the end of the year. Thanks for the clarification.
I suppose then the last remaining blocker is to make sure DBX internal usage is all py3!

**Comment by flying-sheep** [comment]
The pb-jelly-gen readme also still talks about a “python2 script”: https://github.com/dropbox/pb-jelly/blob/master/pb-jelly-gen/README.md

**Comment by nipunn1313** [comment]
Thanks for pointing that out. I believe that reference has been removed now.

**Comment by nipunn1313** [comment]
DBX internal usage is now all py3 - so we can do this! I think we should wait until we get CI set up (#43) - but otherwise looking good

**Comment by nipunn1313** [comment]
This is done with #64 and #65
