### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/pb-jelly#79]
Per https://github.com/github/renaming - we'd like to rename master to main - waiting for github to provide the tools later this year.

**Comment by nipunn1313** [comment]
Tools exist now.

Click "edit" on
https://github.com/dropbox/pb-jelly/branches

Need to be an admin. @ParkMyCar - are you able?

**Comment by ParkMyCar** [comment]
Done! The branch should be renamed from master -> main
